
###

GET http://localhost:3333/tarefas

###

GET http://localhost:3333/tarefas/80556ffb-c894-4c44-8ac3-9288a300a5b0

###

POST http://localhost:3333/tarefas
Content-Type: application/json

{
    "titulo": "Carregar meu celular",
    "descricao": "Tenho que colocar meu celular para carregar",
    "cor": "#FFFFFF"
}

###

PUT http://localhost:3333/tarefas/80556ffb-c894-4c44-8ac3-9288a300a5b0
Content-Type: application/json

{
    "titulo": "Carregar meu pc",
    "descricao": "Tenho que colocar meu pc para carregar, pois está sem bateria",
    "cor": "#000"
}

###

DELETE http://localhost:3333/tarefas/80556ffb-c894-4c44-8ac3-9288a300a5b0
